version: "2.35.1"



services:
  pg_service:
    image: postgres:alpine
    container_name: pg12
    restart: always
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    image: test_image:latest
    container_name: test_con
    restart: always
    command: python main.py
    depends_on:
      - pg_service


volumes:
  pgdata:






